name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]
        os: [ubuntu-latest, windows-latest, macos-latest]
        dependency-version: [prefer-lowest, prefer-stable]

    name: Tests PHP ${{ matrix.php }} on ${{ matrix.os }} with ${{ matrix.dependency-version }} dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

      - name: Execute Tests
        run: composer test:unit